### ISSUE TITLE
Only JavaScript approaches?

### ISSUE THREAD

**Issue by bassjacob** [css-components/spec#1]
Of the listed competing solutions, two are essentially runtime solutions in JS (CSS in JS and inline styles) and two are available to be handled by generic build tools (css + postcss and sass).

Should cross-language be a concern?

**Comment by JedWatson** [comment]
I think that JavaScript is the goal, because that's where the components we're talking about are being implemented. We're talking about a solution for React / Angular / etc. here.

Anything that's handled by generic build tools (e.g. css-modules) implies opinions about the build process, which rules it out (see #3)
